nasa/opera-sds-bach-api

- accountability_api/api_utils/metadata.py
- accountability_api/api_utils/query.py
- accountability_api/api_utils/reporting/production_time_report.py
- accountability_api/api_utils/reporting/retrieval_time_report.py
- accountability_api/v2/ancillary.py
- accountability_api/v2/data.py
- tests/unit/accountability_api/api_utils/reporting/test_incoming_files.py
- tests/unit/accountability_api/v2/test_data.py
update index names
remove size limitations from queries
> Issue 173, issue 161

- accountability_api/api_utils/reporting/production_time_report.py
- accountability_api/api_utils/reporting/retrieval_time_report.py
> issue 185: fix histogram filename

- accountability_api/api_utils/metadata.py
> feat(bach-api): fix typo in comment

- accountability_api/api_utils/metadata.py
- accountability_api/api_utils/reporting/production_time_report.py
> feat(bach-api): fix product count in report. fix landsat 9 parse error

- accountability_api/api_utils/query.py
Refs #307
- correct the number of granules ingested reported
- [FIX] number of granules ingested
-  opera-sds-pcm #307
- verified by manual inspection
> feat(accountability): fix reported number of granules ingested

- README.md
- accountability_api/__init__.py
- accountability_api/setup_loggers.py
- fix bach-api logging. majority of logs not outputting to supervisord log file
- [CHANGE] conditionally configure gunicorn logging integration
- issue-319
- tested on AWS dev cluster
> Issue 319: bach-api logging

- accountability_api/api_utils/reporting/production_time_report.py
- accountability_api/api_utils/reporting/retrieval_time_report.py
- setup.py
- tests/unit/accountability_api/api_utils/reporting/test_production_time_report.py
Refs #28
- fix bug with reports taking too long to generate, causing instance to be unresponsive
- [FIX] mapping of dataset to product
- issue-28
- tested on int environment
> issue 28: feat(report): fix mapping of dataset to products

- README.md
- accountability_api/__init__.py
- accountability_api/api_utils/query.py
- accountability_api/setup_loggers.py
- fix counts displayed in data summary screens in Bach UI
- [FIX] counts displayed in data summary screens in Bach UI
- issue-337
- tested locally against dev cluster DB
> Issue 337: fix data summary counts

- accountability_api/api_utils/reporting/retrieval_time_report.py
Refs #34
- fix report generation failure due to KeyError when an input product has not resulted in an output product.
- [FIX] report generation failure
- issue 34
- tested on dev cluster.
> issue 34: fix(report): fix SLC report generation KeyError

- accountability_api/api_utils/reporting/retrieval_time_report.py
Refs #36
- fix duplicate rows.
- [FIX] duplicate rows
- issue-36
- tested on dev cluster connected to int DB
> fix(report): fix duplicate rows. numbers now separated properly.

- accountability_api/api_utils/reporting/report_util.py
Refs #484
- correct histogram to display 90th percentile
- [FIX] histogram
- https://github.com/nasa/opera-sds-pcm/issues/484
- tested on dev environment
> issue 484: fix(report): fix histogram to show percentile rather than mean.

- accountability_api/api_utils/metadata.py
- accountability_api/api_utils/query.py
- accountability_api/api_utils/reporting/production_time_report.py
- accountability_api/api_utils/reporting/retrieval_time_report.py
- tests/unit/accountability_api/api_utils/reporting/test_production_time_report.py
- tests/unit/accountability_api/api_utils/reporting/test_retrieval_time_report.py
- tests/unit/accountability_api/api_utils/test_utils.py
- tests/unit/accountability_api/test_query.py
- tests/unit/accountability_api/v2/test_data.py
- update bach-api to reference indexes properly under new naming convention that includes dates associated with indexes.
- [CHANGE] support dated indexes.
- issue-552
- tested on dev cluster
> Issue 552: index products by date

- accountability_api/api_utils/reporting/report_util.py
Refs #601
- use different histogram bin method for faster report generation.
- [FIX] slow report generation by changing histogram bin algorithm
- issue-601
- Provide some proof you've tested your changes 
- tested on dev
> issue 601: feat(accountability): use conservative bin method pair, fd and rice.

- accountability_api/api_utils/metadata.py
- accountability_api/api_utils/query.py
- accountability_api/api_utils/reporting/retrieval_time_report.py
- changes required for accountability
- [ADD] support for accountability
- issue-717
- tested on dev cluster and local environment
> issue 717 fix(accountability): DSWx-S1 reports

- accountability_api/api_utils/reporting/retrieval_time_report.py
Refs #717
- fix lookup of id for generating reports
- [FIX] report generation
- Example: issue-717
- tested on local dev using debugger
> Issue 717: fix(accountability): DSWx-S1 reports

- accountability_api/api_utils/reporting/production_time_report.py
Refs #759
- fix production time report
- [FIX] production time report
- issue-759
- tested on local environment
> fix(accountability): production time report

- accountability_api/api_utils/reporting/production_time_report.py
- accountability_api/api_utils/reporting/retrieval_time_report.py
Refs #770
- fix production time report. requires corresponding PR from opera-sds-pcm
- [FIX] production time report
- issue-770
- tested on local environment
> issue 770: fix(accountability): production time report

- accountability_api/v2/data.py
> issue 627: feat(accountability): csv output for data summary

- accountability_api/api_utils/reporting/retrieval_time_report.py
Refs #829
prefer provider date over production datetime
- [FIX] prefer provider date over production datetime
issue-829
tested locally
> issue 829: feat(accountability): prefer provider date

- accountability_api/api_utils/metadata.py
- accountability_api/api_utils/reporting/retrieval_time_report.py
Refs #819
support DISP-S1 reports
- [ADD] support DISP-S1 reports
https://github.com/nasa/opera-sds-pcm/issues/819
- tested locally against int-fwd DB
> feat(accountability): DISP-S1 accountability
